-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost:3306
-- Tiempo de generación: 22-02-2026 a las 10:44:47
-- Versión del servidor: 10.11.15-MariaDB-cll-lve
-- Versión de PHP: 8.4.17

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `mueblesdaso_cob`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `vd`
--

CREATE TABLE `vd` (
  `id_vd` int(200) NOT NULL,
  `contrato` varchar(11) NOT NULL,
  `c_cliente` varchar(60) NOT NULL,
  `nom_cliente` varchar(60) NOT NULL,
  `direccion_c` varchar(80) NOT NULL,
  `ref_entrecalles` varchar(90) NOT NULL,
  `municipio` varchar(80) NOT NULL,
  `tv_casa` varchar(60) NOT NULL,
  `tv_vecindad` text NOT NULL,
  `tv_depa` text NOT NULL,
  `tv_casaplanta2` text NOT NULL,
  `tv_conabierto` text NOT NULL,
  `tv_concerrado` text NOT NULL,
  `sp_gas` text NOT NULL,
  `sp_luz` text NOT NULL,
  `sp_agua` text NOT NULL,
  `sp_tel` text NOT NULL,
  `sp_pavimento` text NOT NULL,
  `sp_terraceria` text NOT NULL,
  `zona` text NOT NULL,
  `vivienda` text NOT NULL,
  `tc_material` text NOT NULL,
  `tc_madera` text NOT NULL,
  `tc_lamina` text NOT NULL,
  `cond_mobiliario` text NOT NULL,
  `mob_dvd` text NOT NULL,
  `mob_computadora` text NOT NULL,
  `mob_modular` text NOT NULL,
  `mob_tv` text NOT NULL,
  `mob_microondas` text NOT NULL,
  `mob_sala` text NOT NULL,
  `mob_comedor` text NOT NULL,
  `mob_refri` text NOT NULL,
  `mob_estufa` text NOT NULL,
  `info_vecinos` text NOT NULL,
  `cliente_obs` text NOT NULL,
  `enganche` text NOT NULL,
  `plazo` text NOT NULL,
  `abono` text NOT NULL,
  `dia_pago` text NOT NULL,
  `codigo_gestor` text NOT NULL,
  `fecha` text NOT NULL,
  `lavadora` text NOT NULL,
  `vd_tel1` varchar(30) NOT NULL,
  `vd_tel2` varchar(30) NOT NULL,
  `latitud` text NOT NULL,
  `longitud` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Volcado de datos para la tabla `vd`
--

INSERT INTO `vd` (`id_vd`, `contrato`, `c_cliente`, `nom_cliente`, `direccion_c`, `ref_entrecalles`, `municipio`, `tv_casa`, `tv_vecindad`, `tv_depa`, `tv_casaplanta2`, `tv_conabierto`, `tv_concerrado`, `sp_gas`, `sp_luz`, `sp_agua`, `sp_tel`, `sp_pavimento`, `sp_terraceria`, `zona`, `vivienda`, `tc_material`, `tc_madera`, `tc_lamina`, `cond_mobiliario`, `mob_dvd`, `mob_computadora`, `mob_modular`, `mob_tv`, `mob_microondas`, `mob_sala`, `mob_comedor`, `mob_refri`, `mob_estufa`, `info_vecinos`, `cliente_obs`, `enganche`, `plazo`, `abono`, `dia_pago`, `codigo_gestor`, `fecha`, `lavadora`, `vd_tel1`, `vd_tel2`, `latitud`, `longitud`) VALUES
(19955, '0', 'DQ2601034', 'MA DE LA LUZ BAUTISTA  GONZALEZ', 'STA INEZ  6 C', 'calle principal ', 'Márquez ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra cliente crédito anterior ago bien cliente estable en domicilio y empleo ok', '800', '60', '250', 'SABADO', 'DQJSP', '2026-01-15', 'LAVADORA', '4422877994', '', '', ''),
(19956, '0', 'DQ2601037', 'MA GABRIELA RIVERA  VILLASE?OR', 'condominio giralda ', 'es tienda da a la calle circuito ', 'Márquez ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra cte a pagado bien es tienda micelenea ok ', '500', ',60', '200', 'MIERCOLES', 'DQJSP', '2026-01-15', 'LAVADORA', '', '', '', ''),
(19957, '0', 'DQ2601042', 'FRANCISCA CLARISA BAUTISTA MENDEZ', 'hda grande 605', 'fin de calle', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '200', '58', '189', 'SABADO', 'DQBOT', '2026-01-20', 'LAVADORA', '4612654573', '', '', ''),
(19958, '0', 'DQ2601043', 'MARGARITA ALVAREZ ESTRELLA', 'loma linda ', '', 'san Juan del Río ', 'CASA', '', '', '', '', '', '', 'LUZ', '', 'TELEFONO', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', 'COMPUTADORA', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-01-20', 'LAVADORA', '', '', '', ''),
(19959, '0', 'DQ2601054', 'OSWALDO AGUILAR ACOSTA', 'águila dorada 104-118', 'águila blanca y aguil asiatica', 'san Juan del rio', '', '', '', 'CASA DOS PLANTAS', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '4000', '', '276', 'LUINES', 'DQBOT', '2026-01-20', 'LAVADORA', '4271197715', '', '', ''),
(19960, '0', 'DQ2601055', 'ISABEL GOMEZ CRUZ', 'Miguel hidalgo #8', 'Guadalupe Victoria y 27 de septiembre ', 'tequisquiapan', '', '', '', 'CASA DOS PLANTAS', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '180', 'MARTES', 'DQRLC', '2026-01-21', 'LAVADORA', '4141223904', '', '', ''),
(19961, '0', 'DQ2601062', 'JUAN AGUSTIN MARIA', 'Melchor ocampo 15', 'fte iglesia', 'Tequisquiapan ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '169', 'MARTES', 'DQRLC', '2026-01-21', 'LAVADORA', '4141389527', '', '', ''),
(19962, '0', 'DQ2601063', 'HIRAM ADVIEL MELENDEZ MARTINEZ', 'hidalgo 46', 'salida a paseo central', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '200', '58', '220', 'MARTES', 'DQRLC', '2026-01-21', 'LAVADORA', '4272429961', '', '', ''),
(19963, '0', 'DQ2601064', 'HIRAM ADVIEL MELENDEZ MARTINEZ', 'hidalgo 46 ', 'salida a paseo central', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', '', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', '', 'MICROONDAS', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '48', '220', 'MARTES', 'DQRLC', '2026-01-21', 'LAVADORA', '4272429961', '', '', ''),
(19964, '0', 'DQ2601060', 'EMMANUEL GONZALEZ CRUZ', 'av Moctezuma 266-a', 'plaza San juan', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '185', 'VIERNES', 'DQRLC', '2026-01-21', 'LAVADORA', '5522561847', '4272261487', '', ''),
(19965, '0', 'DQ2601066', 'GERARDO LOYOLA  ALMARAZ', 'ejido la griega 19', '', 'el marqués ', 'CASA', '', '', '', '', '', '', 'LUZ', '', '', '', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', 'COMPUTADORA', '', '', '', 'SALA', 'COMEDOR', '', '', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-01-22', 'LAVADORA', '', '', '', ''),
(19966, '0', 'DQ2601065', 'GERARDO LOYOLA  ALMARAZ', 'ejido la griega 19', '', 'el marqués ', 'CASA', '', '', '', '', '', '', 'LUZ', '', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', 'COMPUTADORA', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-01-22', 'LAVADORA', '', '', '', ''),
(19967, '0', 'DQ2601061', 'MARIA TERESA TORIBIO AVI?A', 'parcela sn', '', 'el marqués ', 'CASA', '', '', '', '', '', '', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', '', '', 'TV', '', '', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-01-22', 'LAVADORA', '', '', '', ''),
(19968, '0', 'DQ2512099', 'FRANCISCO SAMPAYO MARTINEZ', 'fco i madero s/n', 'carretera al sitio', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '1000', '', '223', 'LUINES', 'DQRLC', '2026-01-22', 'LAVADORA', '7641109754', '', '', ''),
(19969, '0', 'DQ2601059', 'ANDREA POLET CORREA HERNANDEZ', '', '', 'san Juan del río ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', '', 'TELEFONO', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', 'DVD', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-01-22', 'LAVADORA', '', '', '', ''),
(19970, '0', 'DQ2601058', 'JOSE RICARDO SANCHEZ GONZALEZ', 'baella', '', 'Querétaro ', 'CASA', '', '', '', '', '', '', 'LUZ', '', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', 'COMPUTADORA', '', 'TV', '', 'SALA', '', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-01-22', 'LAVADORA', '', '', '', ''),
(19971, '0', 'DQ2601056', 'ANILU HERRERA LUGO', 'mártires de Tacuballa ', '', 'Querétaro ', 'CASA', '', '', '', '', '', 'GAS', '', 'AGUA', 'TELEFONO', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', 'DVD', '', 'MODULAR', '', '', '', 'COMEDOR', '', '', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-01-22', 'LAVADORA', '', '', '', ''),
(19972, '0', 'DQ2601048', 'ANTONIO CRESCENCIO VITE', 'herradura 11', '', 'los héroes ', 'CASA', '', '', '', '', '', 'GAS', '', '', 'TELEFONO', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', 'COMPUTADORA', 'MODULAR', 'TV', '', 'SALA', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-01-22', 'LAVADORA', '', '', '', ''),
(19973, '0', 'DQ2601031', 'YAMEL GUZMAN DAVILA', 'frsnos ', '', 'san Juan del rio ', 'CASA', '', '', '', '', '', '', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', 'DVD', '', 'MODULAR', '', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-01-22', 'LAVADORA', '', '', '', ''),
(19974, '0', 'DQ2601072', 'LORENA ARANGO CRUZ', 'hda murube 507-24', 'hda saltillo', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '150', 'MARTES', 'DQRLC', '2026-01-24', 'LAVADORA', '4271048860', '', '', ''),
(19975, '0', 'DQ2601075', 'JUAN DE JESUS MEDINA ONTIVEROS', 'san Miguel de amazcala sn', 'cancha de FUT bol al frente', 'marquez', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'cliente trabajo en empresa 2 años  casa propia ', '500', '60', '230', 'SABADO', 'DQJSP', '2026-01-24', 'LAVADORA', '44264002705', '', '', ''),
(19976, '0', 'DQ2601069', 'HIRAM ADVIEL MELENDEZ MARTINEZ', 'hidalgo 46', 'camino a paseo central', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '200', '', '100', 'MARTES', 'DQRLC', '2026-01-26', 'LAVADORA', '4272429961', '', '', ''),
(19977, '0', 'DQ2601071', 'VIVIANA SANCHEZ CUESTA', 'ficus 700/23', '', 'Márquez ', 'CASA', '', '', '', '', 'CONDOMINIO CERRADO', 'GAS', 'LUZ', 'AGUA', '', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '200', '60', '220', 'LUINES', 'DQJSP', '2026-01-26', 'LAVADORA', '4424002282', '', '', ''),
(19978, '0', 'DQ2601086', 'DALIA MONTSERRAT GONZALEZ CORONA', 'san Juan ', 'Querétaro ', 'estancia San Juan del Río', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', '', 'MODULAR', 'TV', 'MICROONDAS', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '1000', '12 meses ', '185', 'LUINES', 'DQMIDE', '2026-01-26', 'LAVADORA', '', '', '', ''),
(19979, '0', 'DQ2601040', 'OMAR PI?A UGALDE', 'rio conchos 30', 'rio tuxpan y coatzacoalcos', 'san Juan del rio', 'CASA', '', '', 'CASA DOS PLANTAS', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '200', '', '189', 'LUINES', 'DQBOT', '2026-01-26', 'LAVADORA', '4272907967', '', '', ''),
(19980, '0', 'DQ2601067', 'MARICARMEN SANCHEZ LOPEZ', 'alta tensión ', 'Guadalupe  de más peñas ', 'el rodeo san Juan del Río ', 'CASA', '', '', '', '', '', '', 'LUZ', 'AGUA', 'TELEFONO', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', '', '', '', '', '', '', '', '', 'LO RECOMIENDA', 'es recompra ', '00', '', '280', 'LUINES', 'DQMIDE', '2026-01-26', 'LAVADORA', '', '', '', ''),
(19981, '0', 'DQ2601070', 'ALEJANDRA GUADALUPE RIOS GARDU?O', 'alta tensión ', 'Guadalupe de las peñas ', 'el rodeo san Juan del Río ', '', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', '', '', 'TV', 'MICROONDAS', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'es recompra ', '00', '', '', 'LUINES', 'DQMIDE', '2026-01-26', 'LAVADORA', '', '', '', ''),
(19982, '0', 'DQ2601080', 'JUAN GUTIERREZ MEJIA', 'rio tuxpan 24', 'esq  rio tamessi', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '223', 'LUINES', 'DQRLC', '2026-01-26', 'LAVADORA', '4272746369', '', '', ''),
(19983, '0', 'DQ2601049', 'ANTONIO CRESCENCIO VITE', 'los héroes ', '', 'el marqués ', 'CASA', '', '', '', '', '', '', 'LUZ', '', '', 'PAVIMENTO', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', 'COMPUTADORA', '', '', '', '', 'COMEDOR', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-01-26', 'LAVADORA', '', '', '', ''),
(19984, '0', 'DQ2601009', 'ALONSO HERIBERTO LOREDO NAVARRO', 'cerro del cubilete 9', 'cerro de la estrella ', 'san Juan del rio ', '', '', '', 'CASA DOS PLANTAS', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '500', '', '261', 'SABADO', 'DQBOT', '2026-01-26', 'LAVADORA', '4271111221', '', '', ''),
(19985, '0', 'DQ2601089', 'FRANCISCO JAVIER POLANCO VILLALOBOS', 'rio Ayutla 100', 'esq av Moctezuma', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', '', 'LO RECOMIENDA', '', '300', '58', '180', 'JUEVES', 'DQRLC', '2026-01-27', 'LAVADORA', '4271517439', '', '', ''),
(19986, '0', 'DQ2601078', 'JUAN DOMINGUEZ BAUTISTA', 'hda saltillo 507-12', 'valle sol sur y manantial sur', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', 'MICROONDAS', 'SALA', '', '', 'ESTUFA', 'LO RECOMIENDA', '', '500', '58', '158', 'LUINES', 'DQBOT', '2026-01-27', 'LAVADORA', '4271237705', '', '', ''),
(19987, '0', 'DQ2601094', 'ANDERSON FELIPE BARAJAS DUARTE', 'hda de iturbe 558', 'esq. hda de armilla', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '850', '', '431', 'LUINES', 'DQRLC', '2026-01-27', 'LAVADORA', '4271838733', '', '', ''),
(19988, '0', 'DQ2601093', 'VELVET NAYEL GURRERO CHAVARRIA', 'hda de iturbe 558', 'esq hda de armilla', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '850', '', '431', 'LUINES', 'DQRLC', '2026-01-27', 'LAVADORA', '4272420561', '', '', ''),
(19989, '0', 'DQ2601092', 'KARIME MARQUEZ CABRERA', 'hacienda barralva 503', 'hacienda grande fin de calle', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', 'no salió el cliente para realizar vd...', '', '', '180', 'LUINES', 'DQRLC', '2026-01-28', 'LAVADORA', '7148093471', '', '', ''),
(19990, '0', 'DQ2601076', 'EDUARDO GARCIA SANTIAGO', 'Guanajuato 9', 'puebla y Veracruz ', 'san Juan del rio ', '', '', '', 'CASA DOS PLANTAS', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '400', '', '120', 'SABADO', 'DQBOT', '2026-01-28', 'LAVADORA', '4271032446', '', '', ''),
(19991, '0', 'DQ2601079', 'JUAN BARCENAS BARRON', 'seul 14', 'san José y buenos aires', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '200', '', '155', 'SABADO', 'DQBOT', '2026-01-28', 'LAVADORA', '4271679694', '', '', ''),
(19992, '0', 'DQ2601068', 'MARICARMEN SANCHEZ LOPEZ', 'alta tensión ', 'principales recompra ', '', '', '', '', '', '', '', '', '', '', '', '', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', '', '', '', '', '', '', '', '', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQMIDE', '2026-01-29', 'LAVADORA', '', '', '', ''),
(19993, '0', 'DQ2601081', 'JONATHAN ESTEBAN GONZALEZ ZU?IGA', 'eduardo Luque 10 S', '', 'Hércules ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'cliente estable vive con familia trabajo 3 años ok', '200', '60', '261', 'SABADO', 'DQJSP', '2026-01-29', 'LAVADORA', '4425749993', '', '', ''),
(19994, '0', 'DQ2601046', 'ANTONIO DIAZ MAYAHUA', 'yunkes 213 int 58', '', 'Márquez ', '', '', '', '', '', '', '', '', '', '', '', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', '', '', '', '', '', '', '', '', 'LO RECOMIENDA', 'cliente no tiene tiempo para dar información porque él trabaja todo el día y no hay ningún familiar en su domicilio según el cliente esperé para que me diera fecha y hora y nunca me la dio crédito condicionado a aval pero que no ser vendedor que sea otra persona que tenga ingresos y que tenga propiedad', '', '60', '220', 'LUINES', 'DQJSP', '2026-01-29', 'LAVADORA', '2713900781', '', '', ''),
(19995, '0', 'DQ2601044', 'KARLA PATRICIA MACEDO AVILES', 'orquídea', 'iriz ', 'loma Linda san Juan del Río ', 'CASA', '', '', '', '', '', 'GAS', '', 'AGUA', 'TELEFONO', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', '', '', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '200', '', '', 'LUINES', 'DQMIDE', '2026-01-29', 'LAVADORA', '', '', '', ''),
(19996, '0', 'DQ2601088', 'EVA  AGUIRRE MARTINEZ', 'sendas norponiente annapurna 400/68', '', 'marwuez', 'CASA', '', '', '', '', 'CONDOMINIO CERRADO', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra a la fecha a pagado bien esperemos q siga así ok', '', '60', '201', 'SABADO', 'DQJSP', '2026-01-29', 'LAVADORA', '5610304089', '', '', ''),
(19997, '0', 'DQ2601097', 'MARIA GABRIELA MENDOZA LIZALDE', 'valle frondoso 111', 'esq valle sol sur', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '220', 'LUINES', 'DQRLC', '2026-02-02', 'LAVADORA', '4271623270', '', '', ''),
(19998, '0', 'DQ2601096', 'MARIA GABRIELA MENDOZA LIZALDE', 'valle frondoso 111', 'esq valle sol sur', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '172', 'LUINES', 'DQRLC', '2026-02-02', 'LAVADORA', '4271623270', '', '', ''),
(19999, '0', 'DQ2601117', 'JERONIMO MIRANDA CRUZ', 'juan Juárez 3', 'carretera a cerro gordo', 'san Juan del Río ', '', '', '', 'CASA DOS PLANTAS', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '115', 'LUINES', 'DQBOT', '2026-02-04', 'LAVADORA', '7151151716', '', '', ''),
(20000, '0', 'DQ2601131', 'ELIZABETH VITE VELAZQUEZ', 'privada Alonso de guzman 5b', 'carretera a cerro gordo', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '115', 'SABADO', 'DQRLC', '2026-02-04', 'LAVADORA', '4273859981', '', '', ''),
(20001, '0', 'DQ2601133', 'BEIDELIN SARAI CURIEL VITE', 'alonso de guzman 5b ', 'carretera al sitio', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', '', 'LO RECOMIENDA', '', '500', '', '115', 'LUINES', 'DQRLC', '2026-02-04', 'LAVADORA', '4423958026', '', '', ''),
(20002, '0', 'DQ2601126', 'BRENDA YURIDIA ALVAREZ CRUZ', 'Alonso de guzman 11b', 'carretera al sitio', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '200', '', '180', 'LUINES', 'DQRLC', '2026-02-04', 'LAVADORA', '4271864595', '', '', ''),
(20003, '0', 'DQ2601104', 'MARTIN MORALES MALDONADO', 'rio caracol 1', 'esq rio nilo', 'san Juan del rio ', '', '', '', 'CASA DOS PLANTAS', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '170', 'JUEVES', 'DQRLC', '2026-02-04', 'LAVADORA', '4428208253', '', '', ''),
(20004, '0', 'DQ2601106', 'MARIA DE JESUS NIETO GONZALEZ', 'la trinidad ', '', 'Tequisquiapan ', 'CASA', '', '', '', 'CONDOMINIO ABIERTO', '', '', '', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', '', 'MODULAR', '', '', '', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQCEJ', '2026-02-04', 'LAVADORA', '', '', '', ''),
(20005, '0', 'DQ2601125', 'JOSE FRANCISCO JAVIER ALOSO PACHECO', 'orquídeas 11-A', '', 'marquez ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra cliente estable trabajo y domicilio ok', '', ',60', '292', 'MIERCOLES', 'DQJSP', '2026-02-05', 'LAVADORA', '4428194215', '', '', ''),
(20006, '0', 'DQ2601095', 'ANA TALINA SILVA PEREZ', 'cond vatahdin 400/18', '', 'arwuez', 'CASA', '', '', '', '', 'CONDOMINIO CERRADO', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', 'MODULAR', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra a la fecha cliente a pagado bien ok', '1000', '60', '320', 'LUINES', 'DQJSP', '2026-02-05', 'LAVADORA', '4461459546', '', '', ''),
(20007, '0', 'DQ2601105', 'FABIOLA MONDRAGON RUIZ', 'hda triana 504', 'esq hda ithurbe', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '250', '', '145', 'SABADO', 'DQBOT', '2026-02-05', 'LAVADORA', '4273858188', '', '', ''),
(20008, '0', 'DQ2601121', 'MARTIN ALEJANDRO LUNA VALENCIA', '5 de fab 41', '', 'marquez ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra cliente a pagado bien sin inconveniente ok', '200', '60', '134', 'SABADO', 'DQJSP', '2026-02-05', 'LAVADORA', '4463062057', '', '', ''),
(20009, '0', 'DQ2601108', 'GUSTAVO DIAZ TOLENTINO', 'hda miura 517-6', 'hda grande', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '300', '', '179', 'LUINES', 'DQRLC', '2026-02-05', 'LAVADORA', '4141020381', '', '', ''),
(20010, '0', 'DQ2601112', 'ERICK PINEDA PEREZ', 'hda grande 266', 'hda miura', 'san Jun del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '266', 'LUINES', 'DQBOT', '2026-02-05', 'LAVADORA', '5577110259', '', '', ''),
(20011, '0', 'DQ2601129', 'BERENICE HERRERA MARES', 'cto capricornio 22', 'cto piscis', 'san Juan del Río ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', '', 'TELEFONO', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '180', 'SABADO', 'DQRLC', '2026-02-05', 'LAVADORA', '4271109009', '', '', ''),
(20012, '0', 'DQ2601132', 'KAREN DANIELA FLORES GUADARRAMA', 'Simon nuñez bala 5b', 'carretera al sitio', 'San Juan del Río ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '115', 'SABADO', 'DQRLC', '2026-02-05', 'LAVADORA', '4271618743', '', '', ''),
(20013, '0', 'DQ2601114', 'KARINA GUZMAN CAMACHO', 'gilgeros ', '', 'san Juan del Río ', 'CASA', '', '', 'CASA DOS PLANTAS', '', '', '', '', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', '', 'MODULAR', 'TV', '', '', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-02-06', 'LAVADORA', '', '', '', ''),
(20014, '0', 'DQ2601109', 'MA ANGELA GRANADOS VILLAMIL', 'hda la española 503-24', 'hda grande y hda saltillo', 'san Juan del rio', '', '', 'DEPARTAMENTO', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '300', '60', '166', 'SABADO', 'DQBOT', '2026-02-06', 'LAVADORA', '4271862258', '', '', ''),
(20015, '0', 'DQ2601111', 'REBECA ANGELES GRANADOS', 'loma hermosa 510-18', 'av loma alta', 'san Juan del rio ', '', '', 'DEPARTAMENTO', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '400', '', '200', 'SABADO', 'DQBOT', '2026-02-06', 'LAVADORA', '4272784139', '', '', ''),
(20016, '0', 'DQ2601113', 'JORGE BAYZA MORALES', 'ficus 18', 'roble y cedros', 'san Juan del rio', '', '', '', 'CASA DOS PLANTAS', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', '', 'LO RECOMIENDA', '', '300', '', '172', 'LUINES', 'DQRLC', '2026-02-06', 'LAVADORA', '4272200036', '', '', ''),
(20017, '0', 'DQ2601119', 'JUANA AZUCENA ZAPATA SANCHEZ', 'hidalgo 32', 'esq Agustín melgar', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', '', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '300', '', '220', 'LUINES', 'DQRLC', '2026-02-07', 'LAVADORA', '4272460581', '', '', ''),
(20018, '0', 'DQ2601134', 'JOSE JUAN CARRILLO GARCIA', 'puente de Londres 7', 'av mexico', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', '', 'LO RECOMIENDA', '', '', '', '180', 'LUINES', 'DQBOT', '2026-02-07', 'LAVADORA', '4272762836', '', '', ''),
(20019, '0', 'DP2602003', 'RAMON GARCIA RESENDIZ', 'Gonzalez Rivas ', 'cereso ', 'pueblo quieto san Juan del Río ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', 'TERRACERIA', 'DENTRO DE ZONA', 'REGULAR', 'MATERIAL', '', '', 'BUENO', '', '', '', '', '', '', '', '', '', 'LO RECOMIENDA', 'cliente está de acuerdo con los términos y condiciones', '200', '12 meses ', '250', 'LUINES', 'DQMIDE', '2026-02-10', 'LAVADORA', '', '', '', ''),
(20020, '0', 'DP2602001', 'JENNIFER SILVESTRE ALVAREZ', 'Alonso de guzman 11b ', 'carretera al sitio', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '223', 'LUINES', 'DQRLC', '2026-02-10', 'LAVADORA', '4271901921', '', '', ''),
(20021, '0', 'DP2602021', 'ABIGAIL JOCELYN SALAZAR SANCHEZ', 'lucas lara de cervantes 7-A', 'carretera al sitio', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '150', 'LUINES', 'DQRLC', '2026-02-10', 'LAVADORA', '4272470120', '', '', ''),
(20022, '0', 'DP2602019', 'ROSALINA DE JESUS ROQUE', 'salvador Septién 13-a', 'carretera al sitio', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '200', '', '180', 'LUINES', 'DQRLC', '2026-02-10', 'LAVADORA', '4271149386', '', '', ''),
(20023, '0', 'DP2602025', 'MONICA EDITH PEREZ ESPINDOLA', 'hda de romero 501-3', 'esq hda grande', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '100', 'LUINES', 'DQRLC', '2026-02-10', 'LAVADORA', '5530225938', '', '', ''),
(20024, '0', 'DP2602011', 'NANCY FERNANDA LUGO SANCHEZ', 'hda murube 508-62', 'hda taxquillo y hda grande', 'san Juan del rio', '', '', 'DEPARTAMENTO', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '500', '59', '333', 'LUINES', 'DQBOT', '2026-02-10', 'LAVADORA', '4411218075', '', '', ''),
(20025, '0', 'DP2602010', 'JUAN DIEGO CUELLAR MIRANDA', 'hda murube 508-61', 'hda Saltillo ', 'san Juan del rio', '', '', 'DEPARTAMENTO', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '100', '24', '175', 'LUINES', 'DQBOT', '2026-02-10', 'LAVADORA', '4111779736', '', '', ''),
(20026, '0', 'DP2602014', 'ALEJANDRA IBARRA HERRERA', 'Ricardo Flores Magón sn', '', 'colon ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', '', '', '', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra cliente tiene micelenea ok', '', '60', '388', 'JUEVES', 'DQJSP', '2026-02-10', 'LAVADORA', '4428906856', '', '', ''),
(20027, '0', 'DP2602015', 'MARIA ROSARIO ALICIA HERRERA PAJARO', 'Flores Magón sn ', '', 'colon ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'cliente estable tienen micelanea grande surtida ok', '500', '60', '457', 'JUEVES', 'DQJSP', '2026-02-10', 'LAVADORA', '4425982586', '', '', ''),
(20028, '0', 'DQ2601118', 'YAZMIN CASTILLO CARBAJAL', 'fco y madero sn ', '', 'colon ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra cliente a pagado bien okno dejo el contrato su papá dio la información ', '', '60', '240', 'MARTES', 'DQJSP', '2026-02-10', 'LAVADORA', '5549290361', '', '', ''),
(20029, '0', 'DP2602022', 'DULCE RIVERA CARRASCO', 'cond selles j 7 num 203', 'queda al frente el parque nuevo ', 'marquez ', 'CASA', '', '', '', '', 'CONDOMINIO CERRADO', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'que compra cliente ha pagado bien módulo cerrado pero siempre contesta cuando se le marca por teléfono no veo inconveniente ok', '800', '60', '400', 'SABADO', 'DQJSP', '2026-02-10', 'LAVADORA', '', '', '', ''),
(20030, '0', 'DQ2601073', 'EVER GARCIA RESENDIZ', 'loma del rio 103-26', 'av loma alta', 'san Juan del rio', '', '', '', '', '', 'CONDOMINIO CERRADO', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', 'MODULAR', '', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', 'es privada sin acceso', '', '', '320', 'LUINES', 'DQBOT', '2026-02-11', 'LAVADORA', '4272457590', '', '', ''),
(20031, '0', 'DP2602016', 'MARIA DE JESUS CONCEPCION PIZARRO TORRES', 'girasoles #10', 'azucena ', 'loma Linda san Juan del Río ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', 'COMPUTADORA', 'MODULAR', '', 'MICROONDAS', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'está de acuerdo con su crédito', '', '12 meses ', '300', 'LUINES', 'DQMIDE', '2026-02-11', 'LAVADORA', '', '', '', ''),
(20032, '0', 'DP2602007', 'JESSICA NOLBERTO MARTINEZ', 'azucena 32', 'girasoles ', 'loma Linda San Juan del Río ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', 'COMPUTADORA', '', 'TV', 'MICROONDAS', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'es recompra cliente no se encuentra en el domicilio para hacer verificación', '00', 'año', '300', 'LUINES', 'DQMIDE', '2026-02-11', 'LAVADORA', '', '', '', ''),
(20033, '0', 'DP2602020', 'BLANCA NELY RANGEL MIGUELES', 'esteban García rebollo 36A', 'carretera al sitio', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'cliente renta en la misma calle (#28a)', '100', '', '180', 'SABADO', 'DQRLC', '2026-02-11', 'LAVADORA', '7202309800', '', '', ''),
(20034, '0', 'DQ2601107', 'SANDRA ESTRELLA VEGA', 'nacional 31', '', 'san Juan del Río ', '', 'VECINDAD', '', '', 'CONDOMINIO ABIERTO', '', '', 'LUZ', '', '', '', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', '', 'MODULAR', '', '', 'SALA', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQBOT', '2026-02-11', 'LAVADORA', '', '', '', ''),
(20035, '0', 'DP2602013', 'MARIA MAGDALENA PICHARDO MARTINEZ', 'E. zapata 31', 'esq. pino suarez', 'San Juan del Río ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', '', '', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '500', '', '296', 'LUINES', 'DQRLC', '2026-02-11', 'LAVADORA', '4424228733', '', '', ''),
(20036, '0', 'DP2602034', 'RICARDO ROJAS TAPIA', 'cto cáncer 64', 'cto sagitario', 'san Juan del rio', '', '', '', 'CASA DOS PLANTAS', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '200', '', '230', 'LUINES', 'DQRLC', '2026-02-12', 'LAVADORA', '5636687671', '', '', ''),
(20037, '0', 'DP2602033', 'JUAN MANUEL OLVERA URIBE', 'and tauro 74', 'cto capricornio ', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '169', 'MARTES', 'DQRLC', '2026-02-12', 'LAVADORA', '4272458770', '', '', ''),
(20038, '0', 'DP2602023', 'ADAHY MOLINA RIVERA', 'hda iturbe 504-23', 'av valle sol sur', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '100', 'LUINES', 'DQRLC', '2026-02-13', 'LAVADORA', '5530225938', '', '', ''),
(20039, '0', 'DP2602032', 'MARIA ISABEL BARCENAS MENDOZA', 'priv lucas de lara', 'carretera al sitio', 'san Juan del Río ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', '', 'ESTUFA', 'LO RECOMIENDA', 'cliente dará sus pagos por transferencia ', '', '', '180', 'LUINES', 'DQRLC', '2026-02-14', 'LAVADORA', '4427155221', '', '', ''),
(20040, '0', 'DQ2601110', 'JOSEFINA GARCIA SALAZAR', 'katmandu 8', 'seul y mikael gorbachof', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '200', '', '147', 'SABADO', 'DQRLC', '2026-02-14', 'LAVADORA', '4274279126', '', '', ''),
(20041, '0', 'DP2602035', 'ROSALBA RESENDIZ RAMOS', 'guerrero 15', 'mina y jardin ', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', '', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', 'MICROONDAS', 'SALA', '', '', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '100', 'LUINES', 'DQRLC', '2026-02-16', 'LAVADORA', '4271794494', '', '', ''),
(20042, '0', 'DP2602036', 'ROSALBA RESENDIZ RAMOS', 'guerrero 15 ', 'mina y jardin', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '185', 'LUINES', 'DQRLC', '2026-02-16', 'LAVADORA', '4271794494', '', '', ''),
(20043, '0', 'DP2602039', 'ROSALBA RESENDIZ RAMOS', 'guerrero 15 ', 'mina y jardin', 'san Juan del rio ', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '', '', '', 'LUINES', 'DQRLC', '2026-02-16', 'LAVADORA', '4271794494', '', '', ''),
(20044, '0', 'DP2602040', 'NATALI DE JESUS  DOMINGUEZ BLANCO', 'cond oviedo num6', '', 'marque', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', '', '', '', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'cliente pagará x trasferencia aval darinel de paz ok', '200', '60130', '', 'SABADO', 'DQJSP', '2026-02-18', 'LAVADORA', '7832015238', '', '0', '0'),
(20045, '0', 'DP2602041', 'NATALI DE JESUS DOMINGUEZ BLANCO', 'cond oviedo num 6', 'atrás de escuela', 'Márquez', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', '', '', '', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'que depositara aval darinel ok.', '200', '60', '100', 'SABADO', 'DQJSP', '2026-02-18', 'LAVADORA', '', '', '0', '0'),
(20046, '0', 'DP2602058', 'MARIA JOSE VENTURA ARELLANO', 'el siervo', '', '', '', '', '', '', '', '', '', 'LUZ', '', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', '', '', '', 'BUENO', '', 'COMPUTADORA', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '500', '', '', 'LUINES', 'DQCEJ', '2026-02-18', 'LAVADORA', '', '', '0', '0'),
(20047, '0', 'DP2602043', 'GUILLERMINA MAGOS RIVERA', 'Sonora  sn', '', 'marquez', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra cliente estable crédito anterior lo pago bien sin inconveniente ok', '1500', '60', '240', 'MIERCOLES', 'DQJSP', '2026-02-18', 'LAVADORA', '4422507299', '', '0', '0'),
(20048, '0', 'DP2602063', 'AIDA LORENA TREJO OLVERA', 'hda triana 508-18', 'hda de iturbe', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '100', '', '100', 'LUINES', 'DQRLC', '2026-02-18', 'LAVADORA', '4272884495', '', '0', '0'),
(20049, '0', 'DP2602049', 'MA SOLEDAD RANGEL ARREDONDO', 'río Sonora sn', '', 'marquez', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra cliente a pagado bien estable solvente sin inconveniente', '500', '60', '333', 'MIERCOLES', 'DQJSP', '2026-02-18', 'LAVADORA', '4427100634', '', '0', '0'),
(20050, '0', 'DP2602044', 'GUADALUPE VEGA RAMIREZ', 'domicilio conocido', 'x bslsas', 'Márquez', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'cliente es ama de casa esposo tarimero vive con sus papás', '400', '60', '185', 'SABADO', 'DQJSP', '2026-02-18', 'LAVADORA', '4426108369', '', '0', '0'),
(20051, '0', 'DP2602054', 'FLAVIO ISRAEL GERVACIO HERNANDEZ', 'av central 17', 'fte a tienda 3b', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', '', '500', '', '258', 'SABADO', 'DQRLC', '2026-02-18', 'LAVADORA', '4271151245', '', '0', '0'),
(20052, '0', 'DP2602069', 'ROSALIO HERNANDEZ SANCHEZ', 'Emiliano Zapata', 'salida a  amazcala', 'Márquez', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', '', '', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'recompra cliente pago a bien créditos anteriores sin inconveniente ok', '300', ',60', '150', 'MARTES', 'DQJSP', '2026-02-19', 'LAVADORA', '4464030417', '', '0', '0'),
(20053, '0', 'DP2602073', 'JUAN MANUEL ESQUIVEL CASTRO', 'puente de Venecia 1-A', 'esq puente de Londres', 'san Juan del rio', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', '', 'PAVIMENTO', '', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', '', 'SALA', '', 'REFRIGERADOR', '', 'LO RECOMIENDA', '', '', '', '220', 'SABADO', 'DQRLC', '2026-02-21', 'LAVADORA', '4271196723', '', '0', '0'),
(20054, '0', 'DP2602045', 'MARIA DEL REFUGIO SANCHEZ RESENDIZ', 'el sauz', 'pirul', 'san Sebastián', 'CASA', '', '', '', '', '', 'GAS', 'LUZ', 'AGUA', 'TELEFONO', '', 'TERRACERIA', 'DENTRO DE ZONA', 'EXCELENTE', 'MATERIAL', '', '', 'BUENO', '', '', '', 'TV', 'MICROONDAS', 'SALA', 'COMEDOR', 'REFRIGERADOR', 'ESTUFA', 'LO RECOMIENDA', 'es recompra ok', '', '12', '200', 'LUINES', 'DQMIDE', '2026-02-21', 'LAVADORA', '', '', '0', '0');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `vd`
--
ALTER TABLE `vd`
  ADD PRIMARY KEY (`id_vd`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `vd`
--
ALTER TABLE `vd`
  MODIFY `id_vd` int(200) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20055;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
